import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.57.4";

const SUPABASE_URL=Deno.env.get("SUPABASE_URL")!;
const SERVICE_KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const service=createClient(SUPABASE_URL,SERVICE_KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const MAX_BODY_BYTES=2_500_000;
const TEAM_PREVIEW_SUFFIX="-mobins-projects-4f428afa.vercel.app";
const DEFAULT_ORIGIN="https://dopamine-mobins-projects-4f428afa.vercel.app";
const EXACT_ORIGINS=new Set([
  DEFAULT_ORIGIN,
  "https://dopamine-blond.vercel.app",
  "https://aora-workforce.vercel.app",
  "https://aora-v8-final.vercel.app",
  "https://aora-v8-hardening.vercel.app"
]);

class ApiError extends Error{status:number;code:string;details?:unknown;constructor(status:number,code:string,message:string,details?:unknown){super(message);this.status=status;this.code=code;this.details=details}}
const id=(prefix:string)=>`${prefix}_${crypto.randomUUID().replaceAll("-","")}`;
const now=()=>new Date().toISOString();
const clone=<T>(value:T):T=>structuredClone(value);
const validDate=(value:unknown)=>/^\d{4}-\d{2}-\d{2}$/.test(String(value||""));
const validTime=(value:unknown)=>/^\d{2}:\d{2}$/.test(String(value||""));
const asInt=(value:unknown,fallback=0)=>Number.isFinite(Number(value))?Math.trunc(Number(value)):fallback;
const dateDiff=(from:string,to:string)=>Math.ceil((new Date(`${to}T00:00:00Z`).getTime()-new Date(`${from}T00:00:00Z`).getTime())/86400000);

function allowedOrigin(origin:string|null){if(!origin)return true;if(EXACT_ORIGINS.has(origin))return true;try{const parsed=new globalThis.URL(origin);return ["localhost","127.0.0.1"].includes(parsed.hostname)||(parsed.protocol==="https:"&&parsed.hostname.endsWith(TEAM_PREVIEW_SUFFIX))}catch{return false}}
function cors(origin:string|null){return{"Access-Control-Allow-Origin":origin&&allowedOrigin(origin)?origin:DEFAULT_ORIGIN,"Access-Control-Allow-Headers":"authorization,x-client-info,apikey,content-type","Access-Control-Allow-Methods":"POST,OPTIONS","Access-Control-Max-Age":"600",Vary:"Origin"}}
function response(requestId:string,data:unknown,status=200,origin:string|null=null,version:number|null=null){return new Response(JSON.stringify({request_id:requestId,data,error:null,version,server_time:now()}),{status,headers:{...cors(origin),"content-type":"application/json; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff","referrer-policy":"no-referrer"}})}
function failure(requestId:string,error:unknown,origin:string|null){const e=error instanceof ApiError?error:new ApiError(500,"internal_error",error instanceof Error?error.message:String(error));console.warn("aora-domain-api-rejected",{requestId,status:e.status,code:e.code,message:e.message});return new Response(JSON.stringify({request_id:requestId,data:null,error:{code:e.code,message:e.message,details:e.details||null},version:null,server_time:now()}),{status:e.status,headers:{...cors(origin),"content-type":"application/json; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff","referrer-policy":"no-referrer"}})}

async function one<T=any>(query:PromiseLike<any>,message="Datensatz wurde nicht gefunden."){const{data,error}=await query;if(error)throw new ApiError(500,"database_error",error.message);if(!data)throw new ApiError(404,"not_found",message);return data as T}
async function sessionFor(token:string){if(token.length!==64)throw new ApiError(401,"invalid_session","Sitzungstoken fehlt.");const{data,error}=await service.rpc("validate_demo_session",{p_token:token});if(error||!data?.length)throw new ApiError(401,"invalid_session","Sitzung ist ungültig oder abgelaufen.");const session=data[0];const organization=await one(service.from("organizations").select("id,slug,name,status,timezone").eq("id",session.organization_id).eq("status","active").maybeSingle(),"Organisation ist nicht aktiv.");let accessRole=session.role;let allowedLocationIds:string[]=[];if(session.role==="admin"){const admin=await one(service.from("admins").select("id,payload,role").eq("organization_id",organization.id).eq("id",session.subject_id).maybeSingle(),"Administrationszugang wurde deaktiviert.");accessRole=admin.payload?.scope==="owner"?"owner":"manager";if(accessRole==="owner"){const{data:locations,error:locationError}=await service.from("locations").select("id").eq("organization_id",organization.id).eq("active",true).is("deleted_at",null);if(locationError)throw new ApiError(500,"database_error",locationError.message);allowedLocationIds=(locations||[]).map((item:any)=>String(item.id))}else{const{data:rows,error:accessError}=await service.from("manager_location_access").select("location_id").eq("organization_id",organization.id).eq("manager_id",session.subject_id);if(accessError)throw new ApiError(500,"database_error",accessError.message);allowedLocationIds=(rows||[]).map((item:any)=>String(item.location_id));if(!allowedLocationIds.length)throw new ApiError(403,"location_scope_missing","برای این مدیر هیچ دسترسی مکانی تعریف نشده است.")}}
else if(session.role==="employee"){const employee=await one(service.from("employees").select("id,location_id,primary_location_id,active,deleted_at").eq("organization_id",organization.id).eq("id",session.subject_id).maybeSingle(),"کارمند پیدا نشد.");if(!employee.active||employee.deleted_at)throw new ApiError(403,"employee_inactive","حساب کارمند غیرفعال است.");const{data:rows}=await service.from("employee_location_access").select("location_id").eq("organization_id",organization.id).eq("employee_id",session.subject_id);allowedLocationIds=[...new Set([employee.primary_location_id,employee.location_id,...(rows||[]).map((item:any)=>item.location_id)].filter(Boolean).map(String))]}
else if(session.role==="kiosk"){if(!session.location_id)throw new ApiError(403,"kiosk_location_missing","محل Kiosk مشخص نیست.");allowedLocationIds=[String(session.location_id)]}
return{token,session,organization,accessRole,allowedLocationIds}}
function requireRole(ctx:any,roles:string[]){if(!roles.includes(ctx.accessRole))throw new ApiError(403,"forbidden","برای این عملیات دسترسی کافی وجود ندارد.")}
function requireLocation(ctx:any,locationId:string){if(!ctx.allowedLocationIds.includes(String(locationId)))throw new ApiError(403,"location_forbidden","به این شعبه دسترسی ندارید.")}
function employeeIdFor(ctx:any,input?:unknown){const requested=String(input||ctx.session.subject_id);if(ctx.accessRole==="employee"&&requested!==String(ctx.session.subject_id))throw new ApiError(403,"employee_forbidden","به اطلاعات کارمند دیگری دسترسی ندارید.");return requested}

function stablePercent(input:string){let hash=2166136261;for(const character of input){hash^=character.charCodeAt(0);hash=Math.imul(hash,16777619)}return Math.abs(hash)%100}
async function flagsFor(ctx:any){const{data:base,error}=await service.from("feature_flags").select("flag_key,enabled,location_id,config").eq("organization_id",ctx.organization.id);if(error)throw new ApiError(500,"database_error",error.message);const{data:rules,error:rulesError}=await service.from("feature_flag_rules").select("flag_key,scope_type,scope_value,enabled,rollout_percentage,config").eq("organization_id",ctx.organization.id);if(rulesError)throw new ApiError(500,"database_error",rulesError.message);const output:Record<string,any>={};for(const flag of base||[]){if(flag.location_id&&!ctx.allowedLocationIds.includes(String(flag.location_id)))continue;output[flag.flag_key]={enabled:Boolean(flag.enabled),config:flag.config||{}}}for(const rule of rules||[]){let match=false;if(rule.scope_type==="organization")match=true;if(rule.scope_type==="location")match=ctx.allowedLocationIds.includes(String(rule.scope_value));if(rule.scope_type==="role")match=ctx.accessRole===rule.scope_value;if(rule.scope_type==="employee")match=String(ctx.session.subject_id)===String(rule.scope_value);if(rule.scope_type==="percentage")match=stablePercent(`${ctx.organization.id}:${ctx.session.subject_id}:${rule.flag_key}`)<Number(rule.rollout_percentage||0);if(match)output[rule.flag_key]={enabled:Boolean(rule.enabled),config:rule.config||{},scope:rule.scope_type}}
return output}

function normalizeShift(row:any){const payload=row.payload||{};return{id:row.id,locationId:row.location_id??payload.locationId,employeeId:row.employee_id??payload.employeeId??null,seriesId:row.series_id??payload.seriesId??null,date:String(row.shift_date??payload.date??""),start:String(row.starts_at??payload.start??"").slice(0,5),end:String(row.ends_at??payload.end??"").slice(0,5),breakMinutes:Number(row.break_minutes??payload.breakMinutes??0),roleRequired:row.role_required??payload.roleRequired??null,status:row.status??payload.status??"draft",publishedAt:row.published_at??payload.publishedAt??null,confirmationDeadline:row.confirmation_deadline??payload.confirmationDeadline??null,version:Number(row.version??payload.version??1),deletedAt:row.deleted_at??payload.deletedAt??null}}
function normalizeTimeEntry(row:any){const payload=row.payload||{};return{id:row.id,employeeId:row.employee_id??payload.employeeId,locationId:row.location_id??payload.locationId,date:String(row.entry_date??payload.date??""),startTime:row.start_time??payload.startTime??null,endTime:row.end_time??payload.endTime??null,breakMinutes:Number(row.break_minutes??payload.breakMinutes??0),durationMinutes:Number(row.duration_minutes??payload.durationMinutes??0),status:row.status??payload.status,source:row.source??payload.source,version:Number(row.version||1)}}
function validateRange(from:string,to:string,maxDays:number){if(!validDate(from)||!validDate(to)||dateDiff(from,to)<0||dateDiff(from,to)>maxDays)throw new ApiError(400,"invalid_range",`بازه تاریخ باید حداکثر ${maxDays} روز باشد.`)}

async function calendar(ctx:any,body:any){const from=String(body.from||"");const to=String(body.to||"");validateRange(from,to,62);const employeeId=employeeIdFor(ctx,body.employeeId);if(ctx.accessRole==="manager"||ctx.accessRole==="owner"){const employee=await one(service.from("employees").select("id,location_id,primary_location_id").eq("organization_id",ctx.organization.id).eq("id",employeeId).is("deleted_at",null).maybeSingle(),"کارمند پیدا نشد.");requireLocation(ctx,String(employee.primary_location_id||employee.location_id))}
const{data:shiftRows,error:shiftError}=await service.from("shifts").select("*").eq("organization_id",ctx.organization.id).gte("shift_date",from).lte("shift_date",to).is("deleted_at",null).or(`employee_id.eq.${employeeId},and(employee_id.is.null,status.eq.open)`);if(shiftError)throw new ApiError(500,"database_error",shiftError.message);const allShifts=(shiftRows||[]).map(normalizeShift).filter((item:any)=>item.employeeId===employeeId||(item.employeeId==null&&ctx.allowedLocationIds.includes(String(item.locationId))));
const{data:entryRows,error:entryError}=await service.from("time_entries").select("*").eq("organization_id",ctx.organization.id).eq("employee_id",employeeId).gte("entry_date",from).lte("entry_date",to).is("deleted_at",null);if(entryError)throw new ApiError(500,"database_error",entryError.message);
const{data:assignments,error:assignmentError}=await service.from("task_assignments").select("task_instance_id,status,assigned_at,accepted_at,completed_at").eq("organization_id",ctx.organization.id).eq("employee_id",employeeId);if(assignmentError)throw new ApiError(500,"database_error",assignmentError.message);const taskIds=(assignments||[]).map((item:any)=>item.task_instance_id);let tasks:any[]=[];if(taskIds.length){const{data:taskRows,error:taskError}=await service.from("task_instances").select("*,task_templates(title,category,clockout_policy)").eq("organization_id",ctx.organization.id).in("id",taskIds).gte("instance_date",from).lte("instance_date",to).is("deleted_at",null);if(taskError)throw new ApiError(500,"database_error",taskError.message);tasks=taskRows||[]}
const{data:leaveRows,error:leaveError}=await service.from("leave_requests").select("*").eq("organization_id",ctx.organization.id).eq("employee_id",employeeId);if(leaveError)throw new ApiError(500,"database_error",leaveError.message);
const{data:notes,error:noteError}=await service.from("notifications").select("id,type,title,body,related_entity_type,related_entity_id,read,read_at,created_at,payload").eq("organization_id",ctx.organization.id).eq("employee_id",employeeId).is("deleted_at",null).order("created_at",{ascending:false}).limit(100);if(noteError)throw new ApiError(500,"database_error",noteError.message);
const{data:locations,error:locationError}=await service.from("locations").select("id,name,address,city,country,timezone,latitude,longitude").eq("organization_id",ctx.organization.id).in("id",ctx.allowedLocationIds);if(locationError)throw new ApiError(500,"database_error",locationError.message);
return{from,to,employeeId,shifts:allShifts,timeEntries:(entryRows||[]).map(normalizeTimeEntry),tasks,leaveRequests:leaveRows||[],notifications:notes||[],locations:locations||[]}}

async function scheduleBoard(ctx:any,body:any){requireRole(ctx,["owner","manager"]);const locationId=String(body.locationId||"");requireLocation(ctx,locationId);const from=String(body.from||"");const to=String(body.to||"");validateRange(from,to,31);const[employeesResult,shiftsResult,leaveResult,availabilityResult,staffingResult,requestsResult]=await Promise.all([
 service.from("employees").select("*").eq("organization_id",ctx.organization.id).or(`location_id.eq.${locationId},primary_location_id.eq.${locationId}`).eq("active",true).is("deleted_at",null),
 service.from("shifts").select("*").eq("organization_id",ctx.organization.id).eq("location_id",locationId).gte("shift_date",from).lte("shift_date",to).is("deleted_at",null),
 service.from("leave_requests").select("*").eq("organization_id",ctx.organization.id),
 service.from("availability_rules").select("*").eq("organization_id",ctx.organization.id),
 service.from("staffing_requirements").select("*").eq("organization_id",ctx.organization.id),
 service.from("shift_requests").select("*").eq("organization_id",ctx.organization.id).eq("location_id",locationId).is("deleted_at",null)
]);for(const result of[employeesResult,shiftsResult,leaveResult,availabilityResult,staffingResult,requestsResult])if(result.error)throw new ApiError(500,"database_error",result.error.message);const employees=employeesResult.data||[];const ids=new Set(employees.map((item:any)=>item.id));return{from,to,locationId,employees,shifts:(shiftsResult.data||[]).map(normalizeShift),leaveRequests:(leaveResult.data||[]).filter((item:any)=>ids.has(item.employee_id)),availability:availabilityResult.data||[],staffingRequirements:staffingResult.data||[],shiftRequests:requestsResult.data||[]}}

async function ruleEvaluation(ctx:any,shift:any,excludeId:string|null=null,override:any=null){if(!shift.employeeId)return{valid:true,violations:[],requiresConfirmation:false};const{data:rows,error}=await service.from("shifts").select("id,employee_id,location_id,shift_date,status,payload,starts_at,ends_at,break_minutes").eq("organization_id",ctx.organization.id).eq("employee_id",shift.employeeId).is("deleted_at",null);if(error)throw new ApiError(500,"database_error",error.message);const existing=(rows||[]).map(normalizeShift);const{data,evaluationError}=await service.rpc("aora_evaluate_shift_rules",{p_organization_id:ctx.organization.id,p_employee_id:shift.employeeId,p_location_id:shift.locationId,p_date:shift.date,p_start:shift.start,p_end:shift.end,p_break_minutes:Number(shift.breakMinutes||0),p_existing_shifts:existing,p_exclude_shift_id:excludeId,p_override_reason:override?.confirmed?String(override.reason||""):null,p_actor_type:ctx.accessRole,p_actor_id:ctx.session.subject_id});if(evaluationError)throw new ApiError(500,"rule_engine_error",evaluationError.message);if(!data?.valid)throw new ApiError(data?.requiresConfirmation?428:422,data?.requiresConfirmation?"confirmation_required":"rule_violation",data?.requiresConfirmation?"تأیید و دلیل لازم است.":"این شیفت با یک قانون کاری مسدودکننده تضاد دارد.",data);return data}

async function commitSnapshot(ctx:any,eventType:string,entityType:string,entityId:string,locationId:string|null,mutator:(state:any)=>void){for(let attempt=0;attempt<3;attempt++){const snapshot=await one(service.from("workspace_snapshots").select("state,revision").eq("organization_id",ctx.organization.id).maybeSingle(),"Workspace پیدا نشد.");const state=clone(snapshot.state||{});for(const key of["shifts","shiftRequests","notifications","audit"])if(!Array.isArray(state[key]))state[key]=[];mutator(state);const nextRevision=Number(snapshot.revision)+1;state.meta={...(state.meta||{}),revision:nextRevision,updatedAt:now(),variant:"isolated-v8-final"};const{data,error}=await service.rpc("aora_commit_workspace_state",{p_organization_id:ctx.organization.id,p_expected_revision:Number(snapshot.revision),p_state:state,p_actor_role:ctx.accessRole,p_actor_id:ctx.session.subject_id,p_event_type:eventType,p_event_payload:{entityType,entityId,locationId},p_entity_type:entityType,p_entity_id:entityId,p_location_id:locationId});if(!error&&Number(data)===nextRevision)return{revision:nextRevision,state};if(String(error?.message||"").includes("revision_conflict"))continue;throw new ApiError(500,"snapshot_commit_failed",error?.message||"Workspace ذخیره نشد.")}throw new ApiError(409,"revision_conflict","اطلاعات هم‌زمان تغییر کرده است؛ دوباره تلاش کنید.")}
function shiftInput(body:any){const source=body.shift||{};const employeeId=source.employeeId?String(source.employeeId):null;const locationId=String(source.locationId||"");const date=String(source.date||"");const start=String(source.start||"");const end=String(source.end||"");const breakMinutes=Math.max(0,asInt(source.breakMinutes));if(!locationId||!validDate(date)||!validTime(start)||!validTime(end)||start===end)throw new ApiError(400,"invalid_shift","اطلاعات شیفت ناقص یا نامعتبر است.");return{...source,employeeId,locationId,date,start,end,breakMinutes,status:String(source.status||(employeeId?"draft":"open")),version:Math.max(1,asInt(source.version,1))}}
async function saveShift(ctx:any,body:any,updating=false){requireRole(ctx,["owner","manager"]);const input=shiftInput(body);requireLocation(ctx,input.locationId);const shiftId=updating?String(input.id||body.id||""):id("shift");if(updating&&!shiftId)throw new ApiError(400,"shift_id_missing","شناسه شیفت لازم است.");const evaluation=await ruleEvaluation(ctx,input,updating?shiftId:null,body.ruleOverride);const result=await commitSnapshot(ctx,updating?"UPDATE_SHIFT":"ADD_SHIFT","shift",shiftId,input.locationId,state=>{const index=state.shifts.findIndex((item:any)=>String(item.id)===shiftId);if(updating){if(index<0)throw new ApiError(404,"shift_not_found","شیفت پیدا نشد.");const current=state.shifts[index];const expected=asInt(body.expectedVersion??input.version,1);if(asInt(current.version,1)!==expected)throw new ApiError(409,"version_conflict","نسخه شیفت تغییر کرده است.");state.shifts[index]={...current,...input,id:shiftId,version:expected+1,updatedAt:now(),updatedBy:ctx.session.subject_id,ruleSetId:evaluation.ruleSetId,ruleSetVersion:evaluation.ruleSetVersion,ruleEvaluationId:evaluation.evaluationId}}else{if(state.shifts.some((item:any)=>String(item.id)===shiftId))throw new ApiError(409,"shift_exists","شیفت از قبل وجود دارد.");state.shifts.push({...input,id:shiftId,version:1,createdAt:now(),createdBy:ctx.session.subject_id,ruleSetId:evaluation.ruleSetId,ruleSetVersion:evaluation.ruleSetVersion,ruleEvaluationId:evaluation.evaluationId})}});return{shiftId,revision:result.revision,ruleEvaluation:evaluation}}
async function deleteShift(ctx:any,body:any){requireRole(ctx,["owner","manager"]);const shiftId=String(body.id||"");if(!shiftId)throw new ApiError(400,"shift_id_missing","شناسه شیفت لازم است.");let locationId="";const result=await commitSnapshot(ctx,"DELETE_SHIFT","shift",shiftId,null,state=>{const index=state.shifts.findIndex((item:any)=>String(item.id)===shiftId);if(index<0)throw new ApiError(404,"shift_not_found","شیفت پیدا نشد.");const current=state.shifts[index];locationId=String(current.locationId||"");requireLocation(ctx,locationId);const expected=asInt(body.expectedVersion,asInt(current.version,1));if(asInt(current.version,1)!==expected)throw new ApiError(409,"version_conflict","نسخه شیفت تغییر کرده است.");state.shifts[index]={...current,status:"cancelled",deletedAt:now(),deletedBy:ctx.session.subject_id,deleteReason:String(body.reason||"Vom Dienstplan entfernt"),version:expected+1}});await service.from("shifts").update({status:"cancelled",deleted_at:now(),deleted_by:ctx.session.subject_id,delete_reason:String(body.reason||"Vom Dienstplan entfernt")}).eq("organization_id",ctx.organization.id).eq("id",shiftId);return{shiftId,revision:result.revision}}
async function publishWeek(ctx:any,body:any){requireRole(ctx,["owner","manager"]);const locationId=String(body.locationId||"");requireLocation(ctx,locationId);const from=String(body.from||"");const to=String(body.to||"");validateRange(from,to,7);const publishedAt=now();const result=await commitSnapshot(ctx,"PUBLISH_WEEK","shift_week",`${locationId}:${from}`,locationId,state=>{state.shifts=state.shifts.map((shift:any)=>shift.locationId===locationId&&shift.date>=from&&shift.date<=to&&!shift.deletedAt?{...shift,status:shift.employeeId?"published":"open",publishedAt,version:asInt(shift.version,1)+1,updatedAt:publishedAt,updatedBy:ctx.session.subject_id}:shift)});return{locationId,from,to,publishedAt,revision:result.revision}}
async function copyWeek(ctx:any,body:any){requireRole(ctx,["owner","manager"]);const locationId=String(body.locationId||"");requireLocation(ctx,locationId);const sourceFrom=String(body.sourceFrom||"");const targetFrom=String(body.targetFrom||"");if(!validDate(sourceFrom)||!validDate(targetFrom))throw new ApiError(400,"invalid_date","تاریخ هفته معتبر نیست.");const delta=dateDiff(sourceFrom,targetFrom);const created:string[]=[];const result=await commitSnapshot(ctx,"COPY_WEEK","shift_week",`${locationId}:${targetFrom}`,locationId,state=>{const sourceTo=new Date(`${sourceFrom}T00:00:00Z`);sourceTo.setUTCDate(sourceTo.getUTCDate()+6);const sourceEnd=sourceTo.toISOString().slice(0,10);const copies=state.shifts.filter((shift:any)=>shift.locationId===locationId&&shift.date>=sourceFrom&&shift.date<=sourceEnd&&!shift.deletedAt).map((shift:any)=>{const date=new Date(`${shift.date}T00:00:00Z`);date.setUTCDate(date.getUTCDate()+delta);const newId=id("shift");created.push(newId);return{...shift,id:newId,date:date.toISOString().slice(0,10),status:shift.employeeId?"draft":"open",publishedAt:null,version:1,createdAt:now(),createdBy:ctx.session.subject_id,updatedAt:null,updatedBy:null}});state.shifts.push(...copies)});return{createdShiftIds:created,revision:result.revision}}
async function createSeries(ctx:any,body:any){requireRole(ctx,["owner","manager"]);const input=body.series||{};const locationId=String(input.locationId||"");requireLocation(ctx,locationId);const startsOn=String(input.startsOn||"");const endsOn=String(input.endsOn||"");if(!validDate(startsOn)||!validDate(endsOn)||dateDiff(startsOn,endsOn)<0||dateDiff(startsOn,endsOn)>366)throw new ApiError(400,"invalid_series_range","بازه سری شیفت نامعتبر است.");const recurrence=String(input.recurrence||"weekly");if(!["daily","weekly","biweekly"].includes(recurrence))throw new ApiError(400,"invalid_recurrence","الگوی تکرار پشتیبانی نمی‌شود.");const seriesId=id("series");const generated:any[]=[];for(let cursor=new Date(`${startsOn}T00:00:00Z`),end=new Date(`${endsOn}T00:00:00Z`);cursor<=end;cursor.setUTCDate(cursor.getUTCDate()+(recurrence==="daily"?1:recurrence==="weekly"?7:14))){generated.push({...input,id:id("shift"),seriesId,locationId,date:cursor.toISOString().slice(0,10),start:String(input.start||"08:00"),end:String(input.end||"16:00"),breakMinutes:asInt(input.breakMinutes,30),employeeId:input.employeeId?String(input.employeeId):null,status:input.employeeId?"draft":"open",version:1,createdAt:now(),createdBy:ctx.session.subject_id})}for(const shift of generated)await ruleEvaluation(ctx,shift,null,body.ruleOverride);const{error:seriesError}=await service.from("shift_series").insert({organization_id:ctx.organization.id,id:seriesId,location_id:locationId,employee_id:input.employeeId||null,starts_on:startsOn,ends_on:endsOn,recurrence,recurrence_rule:String(input.recurrenceRule||recurrence),start_time:String(input.start||"08:00"),end_time:String(input.end||"16:00"),break_minutes:asInt(input.breakMinutes,30),active:true,version:1,created_by:ctx.session.subject_id,template:input});if(seriesError)throw new ApiError(500,"series_create_failed",seriesError.message);try{const result=await commitSnapshot(ctx,"CREATE_SHIFT_SERIES","shift_series",seriesId,locationId,state=>state.shifts.push(...generated));return{seriesId,created:generated.length,revision:result.revision}}catch(error){await service.from("shift_series").delete().eq("organization_id",ctx.organization.id).eq("id",seriesId);throw error}}

async function requestOpenShift(ctx:any,body:any){requireRole(ctx,["employee"]);const shiftId=String(body.shiftId||"");const idempotencyKey=String(body.idempotencyKey||crypto.randomUUID());const shift=await one(service.from("shifts").select("*").eq("organization_id",ctx.organization.id).eq("id",shiftId).eq("status","open").is("employee_id",null).is("deleted_at",null).maybeSingle(),"شیفت باز پیدا نشد یا قبلاً رزرو شده است.");requireLocation(ctx,String(shift.location_id));const requestId=id("shift_request");const result=await commitSnapshot(ctx,"REQUEST_OPEN_SHIFT","shift_request",requestId,String(shift.location_id),state=>{const existing=state.shiftRequests.find((item:any)=>item.idempotencyKey===idempotencyKey||(item.shiftId===shiftId&&item.employeeId===ctx.session.subject_id&&item.status==="pending"));if(existing)throw new ApiError(409,"request_exists","برای این شیفت درخواست باز دارید.");state.shiftRequests.push({id:requestId,shiftId,employeeId:ctx.session.subject_id,locationId:shift.location_id,requestType:"open_shift_claim",status:"pending",reason:String(body.reason||""),idempotencyKey,createdAt:now()})});return{requestId,shiftId,revision:result.revision}}
async function decideShiftRequest(ctx:any,body:any){requireRole(ctx,["owner","manager"]);const requestId=String(body.requestId||"");const decision=String(body.decision||"");const key=String(body.idempotencyKey||crypto.randomUUID());const{data,error}=await service.rpc("aora_decide_open_shift_atomic",{p_token:ctx.token,p_request_id:requestId,p_decision:decision,p_reason:String(body.reason||""),p_idempotency_key:key});if(error){const message=error.message||"تصمیم ثبت نشد.";throw new ApiError(message.includes("already")||message.includes("bereits")?409:500,"shift_decision_failed",message)}return data}

async function listTaskTemplates(ctx:any,body:any){requireRole(ctx,["owner","manager"]);const locationId=body.locationId?String(body.locationId):null;if(locationId)requireLocation(ctx,locationId);let query=service.from("task_templates").select("*,task_template_items(*)").eq("organization_id",ctx.organization.id).is("deleted_at",null).order("updated_at",{ascending:false});if(locationId)query=query.or(`location_id.is.null,location_id.eq.${locationId}`);const{data,error}=await query;if(error)throw new ApiError(500,"database_error",error.message);return data||[]}
async function saveTaskTemplate(ctx:any,body:any){requireRole(ctx,["owner","manager"]);const template=body.template||{};const locationId=template.locationId?String(template.locationId):null;if(locationId)requireLocation(ctx,locationId);const templateId=String(template.id||id("task_template"));const version=Math.max(1,asInt(template.version,1));const title=String(template.title||"").trim();if(title.length<2)throw new ApiError(400,"invalid_template","عنوان Template لازم است.");const items=Array.isArray(template.items)?template.items:[];if(!items.length)throw new ApiError(400,"template_items_required","حداقل یک آیتم لازم است.");const row={organization_id:ctx.organization.id,id:templateId,location_id:locationId,title,description:String(template.description||""),category:String(template.category||"custom"),recurrence:"manual",block_clock_out:["MANAGER_OVERRIDE","STRICT_BLOCK"].includes(String(template.clockoutPolicy)),active:template.active!==false,source_version:version,version,created_by:ctx.session.subject_id,updated_by:ctx.session.subject_id,review_required:Boolean(template.reviewRequired),clockout_policy:String(template.clockoutPolicy||"WARN_ONLY"),payload:{...template,items:undefined},updated_at:now()};const{error}=await service.from("task_templates").upsert(row,{onConflict:"organization_id,id"});if(error)throw new ApiError(500,"template_save_failed",error.message);const{error:deleteError}=await service.from("task_template_items").delete().eq("organization_id",ctx.organization.id).eq("template_id",templateId);if(deleteError)throw new ApiError(500,"template_items_failed",deleteError.message);const itemRows=items.map((item:any,index:number)=>({organization_id:ctx.organization.id,template_id:templateId,id:String(item.id||id("item")),position:index,label:String(item.label||"").trim(),answer_type:String(item.type||"checkbox"),required:Boolean(item.required),min_value:item.minValue??null,max_value:item.maxValue??null,options:Array.isArray(item.options)?item.options:[],visibility_rule:item.visibilityRule||{},validation_rule:item.validationRule||{},config:item.config||{}}));const{error:itemError}=await service.from("task_template_items").insert(itemRows);if(itemError)throw new ApiError(500,"template_items_failed",itemError.message);return{templateId,version}}
async function listTaskRules(ctx:any,body:any){requireRole(ctx,["owner","manager"]);const locationId=String(body.locationId||"");requireLocation(ctx,locationId);const{data,error}=await service.from("task_rules").select("*,task_templates(title,category)").eq("organization_id",ctx.organization.id).eq("location_id",locationId).is("deleted_at",null).order("updated_at",{ascending:false});if(error)throw new ApiError(500,"database_error",error.message);return data||[]}
async function saveTaskRule(ctx:any,body:any){requireRole(ctx,["owner","manager"]);const rule=body.rule||{};const locationId=String(rule.locationId||"");requireLocation(ctx,locationId);const ruleId=String(rule.id||id("task_rule"));const row={organization_id:ctx.organization.id,id:ruleId,location_id:locationId,template_id:String(rule.templateId||""),trigger_type:String(rule.triggerType||"manual"),trigger_config:rule.triggerConfig||{},assignment_strategy:String(rule.assignmentStrategy||"all_on_shift"),assignment_config:rule.assignmentConfig||{},due_offset_minutes:asInt(rule.dueOffsetMinutes,0),clockout_policy:String(rule.clockoutPolicy||"WARN_ONLY"),active:rule.active!==false,version:Math.max(1,asInt(rule.version,1)),next_run_at:rule.nextRunAt||null,created_by:ctx.session.subject_id,updated_by:ctx.session.subject_id,updated_at:now()};const{error}=await service.from("task_rules").upsert(row,{onConflict:"organization_id,id"});if(error)throw new ApiError(500,"task_rule_save_failed",error.message);return{ruleId}}
async function listTasks(ctx:any,body:any){const from=String(body.from||new Date().toISOString().slice(0,10));const to=String(body.to||from);validateRange(from,to,62);let employeeId=body.employeeId?String(body.employeeId):null;let locationId=body.locationId?String(body.locationId):null;if(ctx.accessRole==="employee")employeeId=String(ctx.session.subject_id);if(ctx.accessRole==="kiosk")locationId=String(ctx.session.location_id);if(locationId)requireLocation(ctx,locationId);let ids:string[]|null=null;if(employeeId){if(ctx.accessRole==="employee"&&employeeId!==ctx.session.subject_id)throw new ApiError(403,"employee_forbidden","دسترسی مجاز نیست.");const{data:assignments,error}=await service.from("task_assignments").select("task_instance_id").eq("organization_id",ctx.organization.id).eq("employee_id",employeeId);if(error)throw new ApiError(500,"database_error",error.message);ids=(assignments||[]).map((item:any)=>item.task_instance_id);if(!ids.length)return[]}
let query=service.from("task_instances").select("*,task_templates(*),task_assignments(*),task_answers(*),task_evidence(*)").eq("organization_id",ctx.organization.id).gte("instance_date",from).lte("instance_date",to).is("deleted_at",null).order("due_at",{ascending:true});if(locationId)query=query.eq("location_id",locationId);if(ids)query=query.in("id",ids);const{data,error}=await query;if(error)throw new ApiError(500,"database_error",error.message);return data||[]}
async function taskAccess(ctx:any,taskId:string){const task=await one(service.from("task_instances").select("*,task_templates(*),task_assignments(*),task_answers(*),task_evidence(*)").eq("organization_id",ctx.organization.id).eq("id",taskId).is("deleted_at",null).maybeSingle(),"Task پیدا نشد.");requireLocation(ctx,String(task.location_id));if(ctx.accessRole==="employee"&&!task.task_assignments?.some((item:any)=>String(item.employee_id)===String(ctx.session.subject_id)))throw new ApiError(403,"task_forbidden","این Task به شما واگذار نشده است.");return task}
async function saveTaskAnswer(ctx:any,body:any){const taskId=String(body.taskId||"");const itemId=String(body.itemId||"");const task=await taskAccess(ctx,taskId);if(!["open","in_progress","rejected"].includes(task.status))throw new ApiError(409,"task_locked","Task دیگر قابل ویرایش نیست.");const item=await one(service.from("task_template_items").select("*").eq("organization_id",ctx.organization.id).eq("template_id",task.template_id).eq("id",itemId).maybeSingle(),"آیتم Task پیدا نشد.");const value=body.value;const expectedVersion=Math.max(0,asInt(body.expectedVersion,0));const existing=task.task_answers?.find((answer:any)=>answer.template_item_id===itemId);if(existing&&Number(existing.version)!==expectedVersion)throw new ApiError(409,"version_conflict","پاسخ در دستگاه دیگری تغییر کرده است.");if(item.answer_type==="number"){const number=Number(value);if(!Number.isFinite(number))throw new ApiError(400,"invalid_number","مقدار عددی معتبر نیست.");if(item.min_value!=null&&number<Number(item.min_value))throw new ApiError(400,"below_minimum","مقدار کمتر از حد مجاز است.");if(item.max_value!=null&&number>Number(item.max_value))throw new ApiError(400,"above_maximum","مقدار بیشتر از حد مجاز است.")}const employeeId=ctx.accessRole==="employee"?ctx.session.subject_id:String(body.employeeId||task.task_assignments?.[0]?.employee_id||ctx.session.subject_id);const row={organization_id:ctx.organization.id,task_instance_id:taskId,template_item_id:itemId,employee_id:employeeId,value,version:expectedVersion+1,answered_at:now(),updated_at:now()};const{error}=await service.from("task_answers").upsert(row,{onConflict:"organization_id,task_instance_id,template_item_id"});if(error)throw new ApiError(500,"task_answer_failed",error.message);await service.from("task_instances").update({status:"in_progress",version:Number(task.version)+1,updated_at:now()}).eq("organization_id",ctx.organization.id).eq("id",taskId).eq("version",task.version);return{taskId,itemId,version:expectedVersion+1}}
async function evidenceUpload(ctx:any,body:any){const taskId=String(body.taskId||"");const itemId=String(body.itemId||"");const mimeType=String(body.mimeType||"");const fileSize=asInt(body.fileSize,0);const extension=String(body.extension||"jpg").replace(/[^a-z0-9]/gi,"").toLowerCase();const allowed=new Set(["image/jpeg","image/png","image/webp","application/pdf"]);if(!allowed.has(mimeType)||fileSize<=0||fileSize>15728640)throw new ApiError(400,"invalid_evidence","نوع یا حجم فایل مجاز نیست.");const task=await taskAccess(ctx,taskId);const fileId=crypto.randomUUID();const path=`${ctx.organization.id}/${task.location_id}/${taskId}/${itemId}/${fileId}.${extension}`;const{data,error}=await service.storage.from("checklist-evidence").createSignedUploadUrl(path);if(error)throw new ApiError(500,"signed_upload_failed",error.message);return{bucket:"checklist-evidence",path,token:data.token,signedUrl:data.signedUrl}}
async function confirmEvidence(ctx:any,body:any){const taskId=String(body.taskId||"");const itemId=String(body.itemId||"");const path=String(body.path||"");const task=await taskAccess(ctx,taskId);const prefix=`${ctx.organization.id}/${task.location_id}/${taskId}/${itemId}/`;if(!path.startsWith(prefix))throw new ApiError(403,"evidence_path_forbidden","مسیر فایل معتبر نیست.");const parts=path.split("/");const fileName=parts.pop()!;const folder=parts.join("/");const{data:objects,error:listError}=await service.storage.from("checklist-evidence").list(folder,{search:fileName,limit:10});if(listError||!(objects||[]).some((item:any)=>item.name===fileName))throw new ApiError(409,"upload_missing","آپلود فایل تأیید نشد.");const row={organization_id:ctx.organization.id,location_id:task.location_id,task_instance_id:taskId,template_item_id:itemId,uploaded_by:ctx.session.subject_id,storage_path:path,mime_type:String(body.mimeType||"application/octet-stream"),file_size:asInt(body.fileSize,0),sha256:String(body.sha256||""),captured_at:body.capturedAt||null};const{data,error}=await service.from("task_evidence").insert(row).select("id").single();if(error)throw new ApiError(500,"evidence_confirm_failed",error.message);return{evidenceId:data.id,path}}
async function submitTask(ctx:any,body:any){const taskId=String(body.taskId||"");const task=await taskAccess(ctx,taskId);const items=task.task_templates?.task_template_items||await listTemplateItems(ctx,task.template_id);const answers=task.task_answers||[];const evidence=task.task_evidence||[];const missing=[];for(const item of items){if(!item.required)continue;if(item.answer_type==="photo"){if(!evidence.some((file:any)=>file.template_item_id===item.id&&!file.deleted_at))missing.push(item.label)}else if(!answers.some((answer:any)=>answer.template_item_id===item.id&&answer.value!==null&&answer.value!==""))missing.push(item.label)}if(missing.length)throw new ApiError(422,"required_items_missing","موارد الزامی تکمیل نشده‌اند.",{missing});const reviewRequired=Boolean(task.task_templates?.review_required);const nextStatus=reviewRequired?"submitted":"completed";const{data,error}=await service.from("task_instances").update({status:nextStatus,completed_at:nextStatus==="completed"?now():null,version:Number(task.version)+1,updated_at:now()}).eq("organization_id",ctx.organization.id).eq("id",taskId).eq("version",task.version).select("id").maybeSingle();if(error||!data)throw new ApiError(409,"version_conflict",error?.message||"Task هم‌زمان تغییر کرده است.");await service.from("task_assignments").update({status:nextStatus==="completed"?"completed":"in_progress",completed_at:nextStatus==="completed"?now():null}).eq("organization_id",ctx.organization.id).eq("task_instance_id",taskId).eq("employee_id",ctx.session.subject_id);return{taskId,status:nextStatus,version:Number(task.version)+1}}
async function listTemplateItems(ctx:any,templateId:string){const{data,error}=await service.from("task_template_items").select("*").eq("organization_id",ctx.organization.id).eq("template_id",templateId).order("position");if(error)throw new ApiError(500,"database_error",error.message);return data||[]}
async function reviewTask(ctx:any,body:any){requireRole(ctx,["owner","manager"]);const taskId=String(body.taskId||"");const decision=String(body.decision||"");if(!["completed","rejected","waived"].includes(decision))throw new ApiError(400,"invalid_decision","تصمیم معتبر نیست.");const task=await taskAccess(ctx,taskId);const{data,error}=await service.from("task_instances").update({status:decision,reviewed_at:now(),reviewed_by:ctx.session.subject_id,version:Number(task.version)+1,updated_at:now(),completed_at:decision==="completed"?now():task.completed_at,payload:{...(task.payload||{}),reviewReason:String(body.reason||"")}}).eq("organization_id",ctx.organization.id).eq("id",taskId).eq("version",task.version).select("id").maybeSingle();if(error||!data)throw new ApiError(409,"version_conflict",error?.message||"Task هم‌زمان تغییر کرده است.");return{taskId,status:decision}}
async function clockoutGate(ctx:any,body:any){const employeeId=String(body.employeeId||ctx.session.subject_id);const locationId=String(body.locationId||ctx.session.location_id||"");requireLocation(ctx,locationId);const{data,error}=await service.rpc("aora_clockout_gate",{p_token:ctx.token,p_employee_id:employeeId,p_location_id:locationId,p_shift_id:body.shiftId||null});if(error)throw new ApiError(500,"clockout_gate_failed",error.message);return data}
async function managerOverride(ctx:any,body:any){requireRole(ctx,["owner","manager"]);const employeeId=String(body.employeeId||"");const locationId=String(body.locationId||"");const reason=String(body.reason||"").trim();requireLocation(ctx,locationId);if(reason.length<5)throw new ApiError(400,"override_reason_required","دلیل Override باید نوشته شود.");const taskIds=Array.isArray(body.taskIds)?body.taskIds.map(String):[];if(!taskIds.length)throw new ApiError(400,"task_ids_required","Task مسدودکننده مشخص نشده است.");const{data:tasks,error:taskError}=await service.from("task_instances").select("id,status,location_id,version").eq("organization_id",ctx.organization.id).in("id",taskIds);if(taskError)throw new ApiError(500,"database_error",taskError.message);if((tasks||[]).some((task:any)=>task.location_id!==locationId))throw new ApiError(403,"task_location_forbidden","Task مربوط به شعبه دیگری است.");const{error}=await service.from("task_instances").update({status:"waived",reviewed_at:now(),reviewed_by:ctx.session.subject_id,updated_at:now(),payload:{overrideReason:reason,overrideEmployeeId:employeeId}}).eq("organization_id",ctx.organization.id).in("id",taskIds);if(error)throw new ApiError(500,"override_failed",error.message);await service.from("audit_logs").insert({organization_id:ctx.organization.id,id:id("audit"),location_id:locationId,action:"CLOCKOUT_TASK_OVERRIDE",actor:ctx.session.subject_id,actor_type:"admin",actor_id:ctx.session.subject_id,entity:"task_instances",entity_type:"task_instances",entity_id:taskIds.join(","),created_at:now(),payload:{employeeId,taskIds,reason},metadata:{managerOverride:true}});return{employeeId,taskIds,overridden:true}}

async function savePushSubscription(ctx:any,body:any){requireRole(ctx,["employee"]);const subscription=body.subscription||{};const endpoint=String(subscription.endpoint||"");const p256dh=String(subscription.keys?.p256dh||"");const authSecret=String(subscription.keys?.auth||"");if(!endpoint.startsWith("https://")||!p256dh||!authSecret)throw new ApiError(400,"invalid_subscription","Push Subscription معتبر نیست.");const hash=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(endpoint));const row={organization_id:ctx.organization.id,employee_id:ctx.session.subject_id,endpoint,endpoint_hash:new Uint8Array(hash),p256dh,auth_secret:authSecret,user_agent:String(body.userAgent||""),active:true,last_used_at:now(),revoked_at:null};const{error}=await service.from("push_subscriptions").upsert(row,{onConflict:"organization_id,endpoint_hash"});if(error)throw new ApiError(500,"push_subscription_failed",error.message);return{subscribed:true}}
async function removePushSubscription(ctx:any,body:any){requireRole(ctx,["employee"]);const endpoint=String(body.endpoint||"");const hash=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(endpoint));const{error}=await service.from("push_subscriptions").update({active:false,revoked_at:now()}).eq("organization_id",ctx.organization.id).eq("employee_id",ctx.session.subject_id).eq("endpoint_hash",new Uint8Array(hash));if(error)throw new ApiError(500,"push_unsubscribe_failed",error.message);return{subscribed:false}}
async function markNotificationRead(ctx:any,body:any){const notificationId=String(body.notificationId||"");let query=service.from("notifications").update({read:true,read_at:now()}).eq("organization_id",ctx.organization.id).eq("id",notificationId);if(ctx.accessRole==="employee")query=query.eq("employee_id",ctx.session.subject_id);const{data,error}=await query.select("id").maybeSingle();if(error||!data)throw new ApiError(404,"notification_not_found",error?.message||"Notification پیدا نشد.");return{notificationId,read:true}}
async function updateFeatureFlag(ctx:any,body:any){requireRole(ctx,["owner"]);const flagKey=String(body.flagKey||"");if(!/^[a-z][a-z0-9_]{2,63}$/.test(flagKey))throw new ApiError(400,"invalid_flag","Feature Flag معتبر نیست.");const scopeType=String(body.scopeType||"organization");const scopeValue=body.scopeValue==null?null:String(body.scopeValue);const row={organization_id:ctx.organization.id,flag_key:flagKey,scope_type:scopeType,scope_value:scopeValue,enabled:Boolean(body.enabled),rollout_percentage:Math.min(100,Math.max(0,asInt(body.rolloutPercentage,100))),config:body.config||{},updated_at:now()};const{error}=await service.from("feature_flag_rules").upsert(row,{onConflict:"organization_id,flag_key,scope_type,scope_value"});if(error)throw new ApiError(500,"feature_flag_failed",error.message);return{flagKey,scopeType,scopeValue,enabled:Boolean(body.enabled)}}

Deno.serve(async(request:Request)=>{const requestId=request.headers.get("x-request-id")||crypto.randomUUID();const origin=request.headers.get("origin");if(request.method==="OPTIONS")return new Response("ok",{headers:cors(origin)});if(request.method!=="POST")return failure(requestId,new ApiError(405,"method_not_allowed","Method not allowed"),origin);if(origin&&!allowedOrigin(origin))return failure(requestId,new ApiError(403,"origin_forbidden","Origin not allowed"),origin);const length=Number(request.headers.get("content-length")||0);if(length>MAX_BODY_BYTES)return failure(requestId,new ApiError(413,"request_too_large","Request too large"),origin);try{const body=await request.json();const action=String(body.action||"");if(action==="health")return response(requestId,{ok:true,service:"aora-v8-domain-api"},200,origin);const ctx=await sessionFor(String(body.token||""));let data:any;switch(action){case"flags":data=await flagsFor(ctx);break;case"calendar":data=await calendar(ctx,body);break;case"scheduleBoard":data=await scheduleBoard(ctx,body);break;case"createShift":data=await saveShift(ctx,body,false);break;case"updateShift":data=await saveShift(ctx,body,true);break;case"deleteShift":data=await deleteShift(ctx,body);break;case"publishWeek":data=await publishWeek(ctx,body);break;case"copyWeek":data=await copyWeek(ctx,body);break;case"createShiftSeries":data=await createSeries(ctx,body);break;case"requestOpenShift":data=await requestOpenShift(ctx,body);break;case"decideShiftRequest":data=await decideShiftRequest(ctx,body);break;case"taskTemplates":data=await listTaskTemplates(ctx,body);break;case"saveTaskTemplate":data=await saveTaskTemplate(ctx,body);break;case"taskRules":data=await listTaskRules(ctx,body);break;case"saveTaskRule":data=await saveTaskRule(ctx,body);break;case"tasks":data=await listTasks(ctx,body);break;case"saveTaskAnswer":data=await saveTaskAnswer(ctx,body);break;case"evidenceUpload":data=await evidenceUpload(ctx,body);break;case"confirmEvidence":data=await confirmEvidence(ctx,body);break;case"submitTask":data=await submitTask(ctx,body);break;case"reviewTask":data=await reviewTask(ctx,body);break;case"clockoutGate":data=await clockoutGate(ctx,body);break;case"managerOverride":data=await managerOverride(ctx,body);break;case"pushSubscribe":data=await savePushSubscription(ctx,body);break;case"pushUnsubscribe":data=await removePushSubscription(ctx,body);break;case"markNotificationRead":data=await markNotificationRead(ctx,body);break;case"updateFeatureFlag":data=await updateFeatureFlag(ctx,body);break;default:throw new ApiError(400,"unknown_action","عملیات شناخته‌شده نیست.")}return response(requestId,data,200,origin,data?.version??null)}catch(error){return failure(requestId,error,origin)}});
