import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.57.4";

const URL=Deno.env.get("SUPABASE_URL")!;
const KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const db=createClient(URL,KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const WINDOW_PAST_MS=10*60*1000;
const WINDOW_FUTURE_MS=5*60*1000;
const MAX_RULES=500;

const nowIso=()=>new Date().toISOString();
const id=(prefix:string)=>`${prefix}_${crypto.randomUUID().replaceAll("-","")}`;
const asTime=(value:unknown)=>/^\d{2}:\d{2}$/.test(String(value||""))?String(value):null;
const minutes=(value:unknown)=>Number.isFinite(Number(value))?Math.trunc(Number(value)):0;
const weekdayKeys=["sun","mon","tue","wed","thu","fri","sat"];

async function secret(name:string){const{data,error}=await db.rpc("aora_get_runtime_secret",{p_name:name});if(error)throw new Error(error.message);return String(data||"")}
function json(data:unknown,status=200){return new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}})}
function localParts(date:Date,timeZone:string){const parts=new Intl.DateTimeFormat("en-CA",{timeZone,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",second:"2-digit",hourCycle:"h23",weekday:"short"}).formatToParts(date);const map=Object.fromEntries(parts.map(part=>[part.type,part.value]));return{date:`${map.year}-${map.month}-${map.day}`,time:`${map.hour}:${map.minute}`,weekday:String(map.weekday||"").slice(0,3).toLowerCase(),year:Number(map.year),month:Number(map.month),day:Number(map.day),hour:Number(map.hour),minute:Number(map.minute),second:Number(map.second)}}
function zoneOffsetMs(date:Date,timeZone:string){const p=localParts(date,timeZone);return Date.UTC(p.year,p.month-1,p.day,p.hour,p.minute,p.second)-date.getTime()}
function zonedDateTime(dateText:string,timeText:string,timeZone:string){const[y,m,d]=dateText.split("-").map(Number);const[h,min]=timeText.split(":").map(Number);let stamp=Date.UTC(y,m-1,d,h,min,0);for(let i=0;i<3;i++)stamp=Date.UTC(y,m-1,d,h,min,0)-zoneOffsetMs(new Date(stamp),timeZone);return new Date(stamp)}
function addDays(dateText:string,days:number){const date=new Date(`${dateText}T00:00:00Z`);date.setUTCDate(date.getUTCDate()+days);return date.toISOString().slice(0,10)}
function inWindow(candidate:Date,runAt:Date){return candidate.getTime()>=runAt.getTime()-WINDOW_PAST_MS&&candidate.getTime()<=runAt.getTime()+WINDOW_FUTURE_MS}
function statusEligible(status:string){return["published","confirmed","pending_confirmation"].includes(status)}
function normalizedShift(row:any){const payload=row.payload||{};return{id:String(row.id),employeeId:row.employee_id??payload.employeeId??null,locationId:String(row.location_id??payload.locationId??""),date:String(row.shift_date??payload.date??""),start:String(row.starts_at??payload.start??"").slice(0,5),end:String(row.ends_at??payload.end??"").slice(0,5),status:String(row.status??payload.status??"draft"),role:String(payload.roleRequired||"")}}
function shiftBounds(shift:any,timeZone:string){const start=zonedDateTime(shift.date,shift.start,timeZone);let end=zonedDateTime(shift.date,shift.end,timeZone);if(end<=start)end=zonedDateTime(addDays(shift.date,1),shift.end,timeZone);return{start,end}}
function ruleCandidates(rule:any,location:any,shifts:any[],runAt:Date){const timeZone=String(location.timezone||"Europe/Berlin");const candidates:{scheduledFor:Date,shiftId:string|null,localDate:string}[]=[];const config=rule.trigger_config||{};const localToday=localParts(runAt,timeZone).date;const dates=[addDays(localToday,-1),localToday,addDays(localToday,1)];
  if(rule.trigger_type==="fixed_time"){const time=asTime(config.time);if(!time)return candidates;for(const date of dates){const candidate=zonedDateTime(date,time,timeZone);const key=localParts(candidate,timeZone).weekday;const allowed=Array.isArray(config.weekdays)?config.weekdays.map((item:any)=>String(item).toLowerCase()):null;if((!allowed||!allowed.length||allowed.includes(key)||allowed.includes(String(weekdayKeys.indexOf(key))))&&inWindow(candidate,runAt))candidates.push({scheduledFor:candidate,shiftId:null,localDate:date})}}
  if(["shift_start","shift_end","before_shift_end","after_shift_start"].includes(rule.trigger_type)){for(const shift of shifts.filter(item=>item.locationId===rule.location_id&&item.employeeId&&statusEligible(item.status))){const bounds=shiftBounds(shift,timeZone);let candidate=rule.trigger_type.includes("end")?bounds.end:bounds.start;const offset=Math.abs(minutes(config.minutes??rule.due_offset_minutes));if(rule.trigger_type==="before_shift_end")candidate=new Date(bounds.end.getTime()-offset*60000);if(rule.trigger_type==="after_shift_start")candidate=new Date(bounds.start.getTime()+offset*60000);if(inWindow(candidate,runAt))candidates.push({scheduledFor:candidate,shiftId:shift.id,localDate:localParts(candidate,timeZone).date})}}
  if(["location_open","location_close"].includes(rule.trigger_type)){const hours=location.payload?.openingHours||{};for(const date of dates){const weekday=localParts(zonedDateTime(date,"12:00",timeZone),timeZone).weekday;const entry=hours[weekday]||hours[String(weekdayKeys.indexOf(weekday))]||null;const value=entry&&(rule.trigger_type==="location_open"?(entry.open||entry.start):(entry.close||entry.end));const time=asTime(value);if(!time)continue;const candidate=zonedDateTime(date,time,timeZone);if(inWindow(candidate,runAt))candidates.push({scheduledFor:candidate,shiftId:null,localDate:date})}}
  return candidates}
async function employeesAt(ctx:{organizationId:string,locationId:string,scheduledFor:Date,shifts:any[],strategy:string,config:any}){const{organizationId,locationId,scheduledFor,shifts,strategy,config}=ctx;const{data:employees,error}=await db.from("employees").select("id,name,role,role_title,location_id,primary_location_id,active,deleted_at").eq("organization_id",organizationId).eq("active",true).is("deleted_at",null);if(error)throw new Error(error.message);const eligible=(employees||[]).filter((employee:any)=>[employee.primary_location_id,employee.location_id].includes(locationId));const onShiftIds=new Set(shifts.filter(shift=>{if(shift.locationId!==locationId||!shift.employeeId||!statusEligible(shift.status))return false;const bounds=shiftBounds(shift,String(config.timeZone||"Europe/Berlin"));return scheduledFor>=bounds.start&&scheduledFor<=bounds.end}).map(shift=>String(shift.employeeId)));
  if(strategy==="specific_employee")return eligible.filter((employee:any)=>String(employee.id)===String(config.employeeId)).map((employee:any)=>String(employee.id));
  if(strategy==="specific_role")return eligible.filter((employee:any)=>String(employee.role_title||employee.role||"").toLowerCase()===String(config.role||"").toLowerCase()&&(!onShiftIds.size||onShiftIds.has(String(employee.id)))).map((employee:any)=>String(employee.id));
  const onShift=eligible.filter((employee:any)=>onShiftIds.has(String(employee.id)));
  if(strategy==="shift_leader")return onShift.filter((employee:any)=>/lead|leiter|manager/i.test(String(employee.role_title||employee.role||""))).slice(0,1).map((employee:any)=>String(employee.id));
  if(strategy==="one_on_shift")return onShift.slice(0,1).map((employee:any)=>String(employee.id));
  if(strategy==="round_robin"){if(!onShift.length)return[];const index=Math.abs(Math.floor(scheduledFor.getTime()/60000))%onShift.length;return[String(onShift[index].id)]}
  if(strategy==="first_claim")return[null];
  return onShift.map((employee:any)=>String(employee.id))}
async function createNotification(organizationId:string,employeeId:string,locationId:string,taskId:string,title:string,dueAt:string){const notificationId=id("note");const idempotencyKey=`task:${taskId}:employee:${employeeId}`;const{error}=await db.from("notifications").upsert({organization_id:organizationId,id:notificationId,employee_id:employeeId,location_id:locationId,type:"task_assigned",title,body:`Fällig bis ${new Date(dueAt).toLocaleString("de-DE")}`,related_entity_type:"task",related_entity_id:taskId,read:false,created_at:nowIso(),payload:{taskId,dueAt},idempotency_key:idempotencyKey},{onConflict:"organization_id,idempotency_key",ignoreDuplicates:true});if(error)throw new Error(error.message);const{data:row}=await db.from("notifications").select("id").eq("organization_id",organizationId).eq("idempotency_key",idempotencyKey).maybeSingle();if(row?.id){await db.from("notification_deliveries").upsert([{organization_id:organizationId,notification_id:row.id,channel:"in_app",status:"delivered",attempts:1,idempotency_key:`${idempotencyKey}:in_app`,sent_at:nowIso(),delivered_at:nowIso()},{organization_id:organizationId,notification_id:row.id,channel:"web_push",status:"pending",attempts:0,idempotency_key:`${idempotencyKey}:web_push`,next_attempt_at:nowIso()}],{onConflict:"organization_id,idempotency_key",ignoreDuplicates:true})}}
async function processRule(rule:any,templates:Map<string,any>,locations:Map<string,any>,shifts:any[],runAt:Date){const location=locations.get(String(rule.location_id));const template=templates.get(String(rule.template_id));if(!location||!template)return{generated:0,notifications:0,errors:["missing_location_or_template"]};const candidates=ruleCandidates(rule,location,shifts,runAt);let generated=0,notifications=0;const errors:string[]=[];for(const candidate of candidates){let assignees:(string|null)[]=[];try{assignees=await employeesAt({organizationId:rule.organization_id,locationId:rule.location_id,scheduledFor:candidate.scheduledFor,shifts,strategy:rule.assignment_strategy,config:{...(rule.assignment_config||{}),timeZone:location.timezone}})}catch(error){errors.push(error instanceof Error?error.message:String(error));continue}if(!assignees.length)continue;for(const employeeId of assignees){const taskId=id("task");const keyRow={organization_id:rule.organization_id,rule_id:rule.id,scheduled_for:candidate.scheduledFor.toISOString(),employee_id:employeeId,task_instance_id:taskId};const{data:key,error:keyError}=await db.from("task_generation_keys").upsert(keyRow,{onConflict:"organization_id,rule_id,scheduled_for,employee_id",ignoreDuplicates:true}).select("id,task_instance_id").maybeSingle();if(keyError){errors.push(keyError.message);continue}if(!key||String(key.task_instance_id)!==taskId)continue;const dueAt=new Date(candidate.scheduledFor.getTime()+minutes(rule.due_offset_minutes)*60000);const{error:taskError}=await db.from("task_instances").insert({organization_id:rule.organization_id,id:taskId,template_id:template.id,template_version:Number(template.version||template.source_version||1),rule_id:rule.id,location_id:rule.location_id,shift_id:candidate.shiftId,instance_date:candidate.localDate,scheduled_for:candidate.scheduledFor.toISOString(),due_at:dueAt.toISOString(),status:"open",blocking_clockout:["MANAGER_OVERRIDE","STRICT_BLOCK"].includes(rule.clockout_policy),version:1,payload:{scheduler:true,assignmentStrategy:rule.assignment_strategy,triggerType:rule.trigger_type},created_at:nowIso(),updated_at:nowIso()});if(taskError){errors.push(taskError.message);continue}generated++;
      if(employeeId){const{error:assignmentError}=await db.from("task_assignments").insert({organization_id:rule.organization_id,task_instance_id:taskId,employee_id:employeeId,status:"assigned",assigned_at:nowIso()});if(assignmentError){errors.push(assignmentError.message);continue}try{await createNotification(rule.organization_id,employeeId,rule.location_id,taskId,template.title,dueAt.toISOString());notifications++}catch(error){errors.push(error instanceof Error?error.message:String(error))}}
      else{const potential=await employeesAt({organizationId:rule.organization_id,locationId:rule.location_id,scheduledFor:candidate.scheduledFor,shifts,strategy:"all_on_shift",config:{timeZone:location.timezone}});for(const candidateEmployee of potential){try{await createNotification(rule.organization_id,String(candidateEmployee),rule.location_id,taskId,`${template.title} – offen`,dueAt.toISOString());notifications++}catch(error){errors.push(error instanceof Error?error.message:String(error))}}}
    }}await db.from("task_rules").update({last_run_at:runAt.toISOString(),updated_at:nowIso()}).eq("organization_id",rule.organization_id).eq("id",rule.id);return{generated,notifications,errors}}

Deno.serve(async request=>{if(request.method!=="POST")return json({error:"method_not_allowed"},405);try{const expected=await secret("aora_scheduler_token");if(!expected||request.headers.get("x-aora-job-token")!==expected)return json({error:"forbidden"},403);const body=await request.json().catch(()=>({}));const runAt=body.scheduled_for?new Date(body.scheduled_for):new Date();if(Number.isNaN(runAt.getTime()))return json({error:"invalid_scheduled_for"},400);const{data:rules,error:rulesError}=await db.from("task_rules").select("*").eq("active",true).is("deleted_at",null).limit(MAX_RULES);if(rulesError)throw new Error(rulesError.message);if(!rules?.length)return json({ok:true,generated:0,notifications:0,errors:0,server_time:nowIso()});const organizationIds=[...new Set(rules.map((rule:any)=>String(rule.organization_id)))];const locationIds=[...new Set(rules.map((rule:any)=>String(rule.location_id)))];const templateIds=[...new Set(rules.map((rule:any)=>String(rule.template_id)))];const localDates=[...new Set(locationIds.flatMap(()=>{const today=runAt.toISOString().slice(0,10);return[addDays(today,-2),addDays(today,2)]}))];const[{data:locations,error:locationError},{data:templates,error:templateError},{data:shiftRows,error:shiftError}]=await Promise.all([
  db.from("locations").select("id,organization_id,name,timezone,payload,active,deleted_at").in("id",locationIds).eq("active",true).is("deleted_at",null),
  db.from("task_templates").select("id,organization_id,title,version,source_version,active,deleted_at").in("id",templateIds).eq("active",true).is("deleted_at",null),
  db.from("shifts").select("id,organization_id,employee_id,location_id,shift_date,starts_at,ends_at,status,payload,deleted_at").in("organization_id",organizationIds).gte("shift_date",localDates[0]).lte("shift_date",localDates[1]).is("deleted_at",null)
]);if(locationError||templateError||shiftError)throw new Error(locationError?.message||templateError?.message||shiftError?.message);const locationMap=new Map((locations||[]).map((item:any)=>[String(item.id),item]));const templateMap=new Map((templates||[]).map((item:any)=>[String(item.id),item]));const shifts=(shiftRows||[]).map(normalizedShift);let generated=0,notifications=0,errorCount=0;const details:any[]=[];for(const rule of rules){const result=await processRule(rule,templateMap,locationMap,shifts,runAt);generated+=result.generated;notifications+=result.notifications;errorCount+=result.errors.length;if(result.errors.length)details.push({ruleId:rule.id,errors:result.errors.slice(0,5)})}await db.from("scheduler_runs").insert({job_type:"task_generation",scheduled_for:runAt.toISOString(),started_at:runAt.toISOString(),completed_at:nowIso(),status:errorCount?(generated?"partial":"failed"):"completed",generated_count:generated,notification_count:notifications,error_count:errorCount,details:{rules:rules.length,errors:details}});return json({ok:errorCount===0,generated,notifications,errors:errorCount,rules:rules.length,server_time:nowIso()},errorCount&&!generated?500:200)}catch(error){console.error("aora-task-scheduler",error);return json({error:"scheduler_failed",message:error instanceof Error?error.message:String(error)},500)}});
