"use strict";
const INVENTORY_FUNCTION="aora-v8-inventory-next";
S.inventoryTab=S.inventoryTab||"overview";S.inventoryAvailabilityCache=S.inventoryAvailabilityCache||{};S.inventoryPageCache=S.inventoryPageCache||{};
async function invRequest(action,body={}){return request(INVENTORY_FUNCTION,{action,...body,token:S.session?.token})}
function invKey(){return`${S.session?.token||"none"}:${S.locationId||"none"}`}
function invAvailability(){return S.inventoryAvailabilityCache[invKey()]||null}
function setInventoryNav(list,show){const i=list.findIndex(x=>x[0]==="inventory");if(i>=0)list.splice(i,1);if(show){const s=list.findIndex(x=>x[0]==="settings");list.splice(s>=0?s:list.length,0,["inventory","Bestand",I.grid])}}
function syncInventoryNav(){const a=invAvailability();if(isOwner())setInventoryNav(ownerNav,Boolean(a?.enabled));else setInventoryNav(managerNav,Boolean(a?.enabled))}
async function ensureAdminInventoryAvailability(){if(!S.session||!["owner","manager"].includes(S.accessRole)||!S.locationId)return;const k=invKey();if(S.inventoryAvailabilityCache[k]!==undefined)return;S.inventoryAvailabilityCache[k]=null;try{S.inventoryAvailabilityCache[k]=await invRequest("availability",{locationId:S.locationId})}catch{S.inventoryAvailabilityCache[k]={enabled:false}}if(S.adminView!=="inventory")renderAdmin()}
const _renderAdmin=renderAdmin;renderAdmin=function(){syncInventoryNav();_renderAdmin();queueMicrotask(ensureAdminInventoryAvailability)};
const _adminTitle=adminTitle;adminTitle=function(){return S.adminView==="inventory"?"Bestand":_adminTitle()};
const _adminView=adminView;adminView=function(){return S.adminView==="inventory"?inventoryPage():_adminView()};
function inventoryTabs(){return`<div class="inventory-tabs">${[["overview","Übersicht"],["stock","Bestand"],["orders","Bestellen"],["receiving","Wareneingang"]].map(([id,l])=>`<button class="${S.inventoryTab===id?"active":""}" data-inv="tab" data-tab="${id}">${l}</button>`).join("")}</div>`}
function inventoryPage(){const a=invAvailability();if(!a)return`<div class="inventory-shell"><div class="inventory-card"><div class="inventory-empty">Zugriff wird geprüft …</div></div></div>`;if(!a.enabled)return`<div class="inventory-shell"><div class="inventory-card"><div class="inventory-empty">Bestand ist für diesen Standort nicht freigeschaltet.</div></div></div>`;const c=S.inventoryPageCache[`${invKey()}:${S.inventoryTab}`];queueMicrotask(()=>loadInventoryTab(false));return`<div class="inventory-shell"><div class="inventory-head"><div><div class="caps muted">Aora Bestand · ${esc(loc(S.locationId)?.name||"")}</div><h1>Bestand</h1><p>Einfach zählen, bestellen, annehmen und scannen.</p></div><div class="inventory-actions"><button class="btn outline" data-inv="refresh">Aktualisieren</button>${S.inventoryTab==="orders"?'<button class="btn" data-inv="new-order">Neue Bestellung</button>':S.inventoryTab!=="receiving"?'<button class="btn" data-inv="start-count">Bestand zählen</button>':""}</div></div>${inventoryTabs()}${c?renderInventoryTab(c):'<div class="inventory-card"><div class="inventory-empty">Bestand wird geladen …</div></div>'}</div>`}
async function loadInventoryTab(force=false){if(S.adminView!=="inventory"||!S.locationId)return;const k=`${invKey()}:${S.inventoryTab}`;if(S.inventoryPageCache[k]&&!force)return;try{let d;if(S.inventoryTab==="overview"){const[o,s]=await Promise.all([invRequest("overview",{locationId:S.locationId}),invRequest("listStock",{locationId:S.locationId})]);d={overview:o,stock:s}}else if(S.inventoryTab==="stock"){const[s,m]=await Promise.all([invRequest("listStock",{locationId:S.locationId}),invRequest("listMovements",{locationId:S.locationId,limit:40})]);d={stock:s,movements:m}}else if(S.inventoryTab==="orders"){const[o,s]=await Promise.all([invRequest("listPurchaseOrders",{locationId:S.locationId}),invRequest("listSuppliers",{locationId:S.locationId})]);d={orders:o,suppliers:s}}else d={orders:await invRequest("listPurchaseOrders",{locationId:S.locationId})};S.inventoryPageCache[k]=d;if(S.adminView==="inventory")renderAdmin()}catch(e){S.inventoryPageCache[k]={error:e.message};renderAdmin()}}
function renderInventoryTab(d){if(d.error)return`<div class="inventory-card"><div class="inventory-empty">${esc(d.error)}</div></div>`;return S.inventoryTab==="overview"?inventoryOverview(d):S.inventoryTab==="stock"?inventoryStock(d):S.inventoryTab==="orders"?inventoryOrders(d):inventoryReceiving(d)}
function invStockRow(x){const low=Number(x.onHand)<=Number(x.reorderPoint||0);return`<div class="inventory-row"><div><strong>${esc(x.name||"Artikel")}</strong><small>${esc(x.sku||"")} · ${esc(x.category||"")}</small></div><div><small>Bestand</small><b>${Number(x.onHand)}</b></div><div><small>PAR</small><b>${x.parLevel??"–"}</b></div><div><small>Meldebestand</small><b>${Number(x.reorderPoint||0)}</b></div><span class="inventory-status ${low?"low":"ok"}">${low?"Niedrig":"OK"}</span></div>`}
function inventoryOverview(d){const o=d.overview||{},items=d.stock?.items||[],low=items.filter(x=>Number(x.onHand)<=Number(x.reorderPoint||0));return`<div class="inventory-kpis"><div class="inventory-kpi"><strong>${o.lowStockCount||0}</strong><span>Artikel niedrig</span></div><div class="inventory-kpi"><strong>${o.openOrderCount||0}</strong><span>Bestellungen offen</span></div><div class="inventory-kpi"><strong>${o.inTransitCount||0}</strong><span>Transfers unterwegs</span></div><div class="inventory-kpi"><strong>${o.pendingPrintCount||0}</strong><span>Etiketten offen</span></div></div><article class="inventory-card"><div class="inventory-card-head"><h2>Niedriger Bestand</h2><button class="link-btn" data-inv="tab" data-tab="orders">Bestellen ${I.arrow}</button></div>${low.slice(0,10).map(invStockRow).join("")||'<div class="inventory-empty">Kein Artikel unter dem Meldebestand.</div>'}</article>`}
function inventoryStock(d){return`<article class="inventory-card"><div class="inventory-card-head"><h2>Aktueller Bestand</h2><div class="inventory-actions"><button class="btn outline" data-inv="employee-access">Scan-Zugriff</button><button class="btn outline" data-inv="start-count">Bestand zählen</button></div></div>${(d.stock?.items||[]).map(invStockRow).join("")||'<div class="inventory-empty">Noch keine Artikel.</div>'}</article>`}
function invStatus(s){return({draft:"Entwurf",ready:"Bereit",sending:"Wird gesendet",submitted:"Bestellt",placed:"Bestellt",send_failed:"Versandfehler",delivered:"Geliefert",partially_received:"Teilweise erhalten",received:"Erhalten",cancelled:"Storniert"})[s]||s}
function inventoryOrders(d){return`<article class="inventory-card"><div class="inventory-card-head"><h2>Bestellungen</h2><div class="inventory-actions"><button class="btn outline" data-inv="suppliers">Lieferanten</button><button class="btn" data-inv="new-order">Neue Bestellung</button></div></div>${(d.orders?.orders||[]).map(o=>`<div class="inventory-order-row"><div><strong>${esc(o.order_number||o.id?.slice(0,8)||"Bestellung")}</strong><small>${esc(o.supplier?.name||"Lieferant")} · ${o.lines?.length||0} Positionen</small></div><span class="inventory-status">${esc(invStatus(o.status))}</span><small>${o.expected_on?`Lieferung ${esc(o.expected_on)}`:""}</small>${["draft","ready","send_failed"].includes(o.status)?`<button class="btn outline" data-inv="send-order" data-id="${o.id}">Senden</button>`:"<span></span>"}</div>`).join("")||'<div class="inventory-empty">Noch keine Bestellung.</div>'}</article>`}
function inventoryReceiving(d){const orders=(d.orders?.orders||[]).filter(o=>["submitted","placed","delivered","partially_received"].includes(o.status));return`<article class="inventory-card"><div class="inventory-card-head"><h2>Wareneingang</h2></div>${orders.map(o=>`<div class="inventory-order-row"><div><strong>${esc(o.order_number||o.id?.slice(0,8))}</strong><small>${esc(o.supplier?.name||"")}</small></div><span class="inventory-status">${esc(invStatus(o.status))}</span><small>${o.expected_on||""}</small><button class="btn outline" data-inv="receive-order" data-id="${o.id}">Annehmen</button></div>`).join("")||'<div class="inventory-empty">Keine erwarteten Lieferungen.</div>'}</article>`}
app.addEventListener("click",e=>{const b=e.target.closest("[data-inv]");if(!b)return;if(b.dataset.inv==="tab"){S.inventoryTab=b.dataset.tab;renderAdmin()}else if(b.dataset.inv==="refresh"){delete S.inventoryPageCache[`${invKey()}:${S.inventoryTab}`];loadInventoryTab(true)}});
