import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.57.4";
import webpush from "npm:web-push@3.6.7";

const URL=Deno.env.get("SUPABASE_URL")!;
const KEY=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const db=createClient(URL,KEY,{auth:{persistSession:false,autoRefreshToken:false}});
const BATCH=100;
const now=()=>new Date().toISOString();
const reply=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}});
async function secret(name:string){const{data,error}=await db.rpc("aora_get_runtime_secret",{p_name:name});if(error)throw new Error(error.message);return String(data||"")}
function destination(notification:any){const type=String(notification.related_entity_type||notification.payload?.relatedEntityType||"");const target=String(notification.related_entity_id||notification.payload?.relatedEntityId||"");if(type==="task"&&target)return`/arbeitnehmer/?task=${encodeURIComponent(target)}`;if(type==="shift"&&target)return`/arbeitnehmer/?shift=${encodeURIComponent(target)}`;if(type==="calendar")return`/arbeitnehmer/?date=${encodeURIComponent(target)}`;return"/arbeitnehmer/"}
function backoff(attempts:number){return Math.min(24*60,Math.max(1,2**Math.min(attempts,10)))*60*1000}

Deno.serve(async request=>{if(request.method!=="POST")return reply({error:"method_not_allowed"},405);try{const expected=await secret("aora_push_dispatch_token");if(!expected||request.headers.get("x-aora-job-token")!==expected)return reply({error:"forbidden"},403);const[publicKey,privateKey]=await Promise.all([secret("aora_vapid_public_key"),secret("aora_vapid_private_key")]);if(!publicKey||!privateKey)throw new Error("VAPID keys are missing");webpush.setVapidDetails("https://dopamine-blond.vercel.app",publicKey,privateKey);
  const{data:deliveries,error:deliveryError}=await db.from("notification_deliveries").select("id,organization_id,notification_id,status,attempts,next_attempt_at").eq("channel","web_push").in("status",["pending","failed"]).or(`next_attempt_at.is.null,next_attempt_at.lte.${now()}`).order("created_at",{ascending:true}).limit(BATCH);if(deliveryError)throw new Error(deliveryError.message);if(!deliveries?.length)return reply({ok:true,processed:0,sent:0,failed:0,expired:0,server_time:now()});
  const notificationIds=[...new Set(deliveries.map((item:any)=>String(item.notification_id)))];const{data:notifications,error:notificationError}=await db.from("notifications").select("id,organization_id,employee_id,location_id,type,title,body,related_entity_type,related_entity_id,payload,deleted_at").in("id",notificationIds).is("deleted_at",null);if(notificationError)throw new Error(notificationError.message);const notificationMap=new Map((notifications||[]).map((item:any)=>[`${item.organization_id}:${item.id}`,item]));let sent=0,failed=0,expired=0;
  for(const delivery of deliveries){const notification=notificationMap.get(`${delivery.organization_id}:${delivery.notification_id}`);if(!notification?.employee_id){await db.from("notification_deliveries").update({status:"cancelled",attempts:Number(delivery.attempts)+1,last_error:"notification_or_employee_missing",updated_at:now()}).eq("id",delivery.id);failed++;continue}
    const{data:subscriptions,error:subscriptionError}=await db.from("push_subscriptions").select("id,endpoint,p256dh,auth_secret,active").eq("organization_id",delivery.organization_id).eq("employee_id",notification.employee_id).eq("active",true);if(subscriptionError){failed++;continue}if(!subscriptions?.length){await db.from("notification_deliveries").update({status:"expired",attempts:Number(delivery.attempts)+1,last_error:"no_active_subscription",updated_at:now()}).eq("id",delivery.id);expired++;continue}
    const payload=JSON.stringify({title:notification.title||"Aora",body:notification.body||"Neue Mitteilung",url:destination(notification),tag:`aora-${notification.id}`,notificationId:notification.id,relatedEntityType:notification.related_entity_type,relatedEntityId:notification.related_entity_id});let successes=0;const errors:string[]=[];
    for(const subscription of subscriptions){try{await webpush.sendNotification({endpoint:subscription.endpoint,keys:{p256dh:subscription.p256dh,auth:subscription.auth_secret}},payload,{TTL:3600,urgency:"normal",topic:String(notification.id).slice(0,32)});successes++;await db.from("push_subscriptions").update({last_used_at:now()}).eq("id",subscription.id)}catch(error:any){const status=Number(error?.statusCode||error?.status||0);if(status===404||status===410){await db.from("push_subscriptions").update({active:false,revoked_at:now()}).eq("id",subscription.id);errors.push(`expired:${status}`)}else errors.push(`delivery:${status||"unknown"}`)}}
    const attempts=Number(delivery.attempts||0)+1;if(successes>0){await db.from("notification_deliveries").update({status:"sent",attempts,last_error:errors.length?errors.join(","):null,sent_at:now(),updated_at:now()}).eq("id",delivery.id);sent++}else if(errors.length&&errors.every(item=>item.startsWith("expired:"))){await db.from("notification_deliveries").update({status:"expired",attempts,last_error:errors.join(","),updated_at:now()}).eq("id",delivery.id);expired++}else{await db.from("notification_deliveries").update({status:attempts>=8?"failed":"pending",attempts,last_error:errors.join(",")||"delivery_failed",next_attempt_at:new Date(Date.now()+backoff(attempts)).toISOString(),updated_at:now()}).eq("id",delivery.id);failed++}}
  return reply({ok:failed===0,processed:deliveries.length,sent,failed,expired,server_time:now()},failed&&sent===0?500:200)}catch(error){console.error("aora-push-dispatch",error instanceof Error?error.message:String(error));return reply({error:"push_dispatch_failed",message:error instanceof Error?error.message:String(error)},500)}});
